### ISSUE TITLE
Error with special chars like ä ö ü

### ISSUE THREAD

**Issue by kriztan** [siacs/HttpUploadComponent#42]
I've tried to send an image with a filename containing an ä and the server sends an error. The file could not be sent.
`2015-08-23 19:06:00,428  DEBUG    RECV: <iq to="upload.domain.de" type="get" id="sagq4ssh3" from="user@domain.de/mobile"><request xmlns="eu:siacs:conversations:http:upload"><filename>Sonntagsspazierg\xe4nge.JPG</filename><size>111852</size><content-type /></request></iq>
2015-08-23 19:06:00,440  DEBUG    Event triggered: request_upload_slot
2015-08-23 19:06:00,445  ERROR    Error processing event handler: <bound method MissingComponent.request_upload_slot of <__main__.MissingComponent object at 0x2a6ad10>>
Traceback (most recent call last):
File "/lib/python3.2/sleekxmpp-1.3.1-py3.2.egg/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner func(*args) 
File "/var/HttpUploadComponent/server.py", line 164, in request_upload_slot
print(path) UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 98: ordinal not in range(128)
2015-08-23 19:06:00,527  ERROR    Error handling {jabber:component:accept}iq stanza
Traceback (most recent call last):
File "/lib/python3.2/sleekxmpp-1.3.1-py3.2.egg/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner func(*args)
File "/var/HttpUploadComponent/server.py", line 164, in request_upload_slot print(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 98: ordinal not in range(128)`

**Comment by lotux** [comment]
sent pull request for this issue

**Comment by iNPUTmice** [comment]
use python3

**Comment by SamWhited** [comment]
> use python3

If this is going to be the recommended advise, can I strip out the Python 2 work arounds I added? No idea why I submitted that PR anyways... it's just more of a pain for everyone.

**Comment by kriztan** [comment]
@iNPUTmice As you can see in the log above in my first post, I'm using python3 and it isn't working.

**Comment by kriztan** [comment]
fixed via 8a2932241b47c465150112851462584cd7c44da3
