### ISSUE TITLE
Sending files over 1MB results in crash.

### ISSUE THREAD

**Issue by Bretos** [siacs/HttpUploadComponent#46]
Hello! I've just set up this component on my prosody server with nginx as proxy.

Works great for small files, but with sizes over 1 MB sending(or client itself) crashes.
With files below 1MB it works perfectly.

Using gajim with it's [plugin](https://trac-plugins.gajim.org/wiki/HttpUploadPlugin) results in a crash:

    *** Error in `python2': double free or corruption (out): 0x00007faa8c12c6e0 ***

Or sometimes it throws an exception:

    Exception in thread Thread-22:
    Traceback (most recent call last):
       File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/usr/lib/python2.7/site-packages/gajim/gui_interface.py", line 3129, in thread_function
        output = func(*func_args)
      File "/home/me/.local/share/gajim/plugins/httpupload/httpupload.py", line 304, in uploader
        transfer = urllib2.urlopen(request)
      File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 437, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 475, in error
        return self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    HTTPError: HTTP Error 413: Request Entity Too Large

and with Conversations(on Android) logcat does not show anything interesting, client itself marks sending the file as failed

    D/conversations(17754): uploading to https://mydomain.tld/xmpp/ca7cb4cf53230a2aa1f427d51f9a53c2484ef21a/UJSNKIRX3HJLDP46HRDKSB0NGGWDZ25XN7FC30F8/filename.ext
    D/conversations(17754): me@domain.tld: acknowledging stanza #467
    I/Timeline( 7375): Timeline: Activity_windows_visible id: ActivityRecord{23ef65b4 u0 eu.siacs.conversations/.ui.ConversationActivity t10} time:36303750
    D/conversations(17754): app switched into background

Nothing unordinary in component logs too, I am afraid!

    2015-09-13 00:26:30,788  DEBUG    RECV: <iq to="upload.domain.tld" type="get" id="3aolktr5ak" from="me@domain.tld/moto"><request xmlns="eu:siacs:conversations:http:upload"><filename>filename.ext</filename><size>3942326</size><content-type xmlns="application/filetype/ya_know" /></request></iq>
    2015-09-13 00:26:30,789  DEBUG    Event triggered: request_upload_slot ca7cb4cf66230a2aa1f427d61f9a12c2484ef21a/Q8RHASTYC9A2FX9LF7D88Y9JY3JBC6D6FOLV2RSB/Filename.ext
    2015-09-13 00:26:30,790  DEBUG    SEND: <iq to="me@domain.tld/mot" type="result" id="3aolktr5ak" from="upload.domain.tld"><slot xmlns="eu:siacs:conversations:http:upload"><get>https://domain.tld/xmpp/ca7cb4cf652330a2aa1f427d51f9a53c2484ef21a/Q8RHASTYC9M0FX9LF7B88Y9JY3JBC6D6FOLV2RSB/FILE</get><put>https://domain.tld/xmpp/ca7cb4cf66230a7aa1f427d51f9a53c2484ef21a/Q8RHASTYC9M0FX9LF7F88Y9JY3JBC6D6FVLV2RSB/FILE.ext</put></slot></iq>

 Did I misconfigure something or dicovered a bug?

@EDIT:
Adding:
            client_max_body_size 200M;
in nginx proxy section seems to have fixed the problem. Gajim however still crashes. Gonna report it in the right place.

**Comment by andersruneson** [comment]
So solved by PR #50?

**Comment by Bretos** [comment]
Exactly

**Comment by SamWhited** [comment]
No, it shouldn't cause a crash regardless of nginx's max body size.

**Comment by Bretos** [comment]
@SamWhited it does not. Probably Gajim's plugin has an undocumented bug. Sending anything through conversations works great.

**Comment by iNPUTmice** [comment]
But its gajim that's crashing right? So I guess I can close here?

**Comment by SamWhited** [comment]
Yah, my mistake. I assumed it was the server crashing when I saw the crash report.
